name: nost
description: A unique storytelling travel app.

publish_to: 'none'
version: 1.0.0+16

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.0.2
  package_info_plus: ^5.0.1
  envied: ^0.5.2
  logger: ^2.0.2+1
  flutter_riverpod: ^2.4.6
  riverpod_annotation: ^2.3.1
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  go_router: ^13.0.0
  permission_handler: ^11.0.1
  hooks_riverpod: ^2.4.6
  flutter_hooks: ^0.20.3
  equatable: ^2.0.5
  path_provider: ^2.1.1
  flutter_inappwebview: ^6.0.0
  url_launcher: ^6.2.1
  image_picker: ^1.0.4
  flutter_svg: ^2.0.9
  retrofit: ^4.0.3
  dio: ^5.3.3
  uuid: ^4.2.1
  slang: ^3.25.0
  slang_flutter: ^3.25.0
  google_sign_in: ^6.1.6
  stacked_listview: ^1.0.4
  badges: ^3.1.2
  flutter_advanced_drawer: ^1.3.5
  font_awesome_flutter: ^10.6.0
  animated_toggle_switch: ^0.8.0
  table_calendar: ^3.0.9
  easy_stepper: ^0.8.2
  settings_ui: ^2.0.2
  hashids2: ^2.0.0
  lite_rolling_switch: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
  build_runner: ^2.4.6
  cider: ^0.2.4
  envied_generator: ^0.5.2
  riverpod_generator: ^2.3.6
  custom_lint: ^0.6.0
  riverpod_lint: ^2.3.4
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  go_router_builder: ^2.3.4
  slang_build_runner: ^3.25.0
  flutter_gen_runner: ^5.3.2
  dot_navigation_bar: ^1.0.2

flutter_gen:
  output: lib/core/gen/

flutter:
  uses-material-design: true
  assets:
    - assets/images/
